### ISSUE TITLE
ENABLE CORS

### ISSUE THREAD

**Issue by GilmarPerez** [qmatic/api-gateway#1]
The **hybrid** applications are taking a strong rise, so it is required to implement **CORS** to access API GATEWAY. We currently have a client installed with Orchestra in 170 offices and has a hybrid application development, through appointments and we would like to implement TAKE TICKET.

Is it possible to implement within the API GATEWAY?

**Comment by pergrapatin** [comment]
What we have done so far is use node.js with a proxy function. See mobile example on sharebox.

**Comment by GilmarPerez** [comment]
Thanks for your answer per, But do you use this is not back to betwixt?, For a test environment I do not see problem, but would this be the recommendation to put it into production?

**Comment by pergrapatin** [comment]
Yes we do recommend having a backend in front of the api gw. It will give you the possibility to have higher security by for example use a captcha and by hiding the token.
