### ISSUE TITLE
Cannot run gateway services

### ISSUE THREAD

**Issue by iqbal-ksa** [qmatic/api-gateway#2]
While start the service an error generated "system cannot find the specified path"

**Comment by GilmarPerez** [comment]
Did you correctly set up your file application.yml ?

**Comment by pergrapatin** [comment]
Try this:

api-gateway-1.2.0.0.bat 
api-gateway-1.2.0.0
these files should have been named like this:
api-gateway.bat 
api-gateway

We fix this shortly

**Comment by iqbal-ksa** [comment]
Thanks for reply, its working with chrome rest client, but when we try to call from ajax its giving 401 forbidden error see header set
example:
$.ajax({
	 type:"GET",
		      url: url,
        headers: { "Content-Type":"application/json","Accept": "application/json","auth-token": access_token }, 
        success: function() {

**Comment by pergrapatin** [comment]
What url are you trying to access and what access does you access_token have. Also what is the "Accept" header for?

**Comment by iqbal-ksa** [comment]
Hi 
see the url send get request to API gateway port 9090
auth-token is api key generated from API gateway
the auth token  tried set header in beforesend event also but same error

$.ajax({
			type: 'GET',
			url: 'http://10.248.185.3:9090/rest/servicepoint/branches/1',
			contentType: 'application/json',
			dataType: 'json',
                        headers: {"auth-token" : "2995ecc1-d8c1-4fcf-b90b-f3210d1d6458"},			
			async: false,
			success: function() {
				alert("Connection Succeed");
			},

**Comment by pergrapatin** [comment]
The following works for me. (generated by postman)

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://XXXX:9090/rest/managementinformation/systemInformation/",
  "method": "GET",
  "headers": {
    "auth-token": "XXXXX",
    "content-type": "application/json",
    "cache-control": "no-cache",
    "postman-token": "db3a21a1-aeb2-be8d-8e8b-9efc15c779d4"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});

**Comment by iqbal-ksa** [comment]
Hi 

I copied the script from Postman and tested, unfortunately the same error we are receiving. 

see the script

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://xx.xx.xx.xx:9090/rest/managementinformation/systemInformation",
  "method": "GET",
  "headers": {
    "auth-token": "2995ecc1-d8c1-4fcf-b90b-f3210d1d6458",
    "content-type": "application/json",
    "cache-control": "no-cache",
    "postman-token": "35087c63-82e5-0077-d384-49b69a3dbe22"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});

see ERR below

2http://xx.xx.xx.xx:9090/rest/managementinformation/systemInformation Failed to load resource: the server responded with a status of 403 (Forbidden)
jj.html:1 XMLHttpRequest cannot load 

http://xx.xx.xx.xx:9090/rest/managementinformation/systemInformation. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xx.xx.xx.xx:8080' is therefore not allowed access. The response had HTTP status code 403.

**Comment by pergrapatin** [comment]
You have a cross site scripting problem. You need a back end to proxy the request. See our mobile example on Sharebox@Qmatic world for a nodeJS example of doing this.
