### ISSUE TITLE
In 6.2 this API has been removed from qsystem

### ISSUE THREAD

**Issue by adam-meadows-qmatic** [qmatic/api-gateway#6]
https://github.com/qmatic/api-gateway/blob/841ff240ec624476a561546129f9f73a6e998531/src/main/resources/application.yml#L119

**Comment by pergrapatin** [comment]
Hi Adam,

We have investigated this and this API has never been exposed centrally (In R5 and forward). It is only available on the agents. We should ofcourse not have included it in the yml file and I will create a jira and we should remove it eventually.

**Comment by jolpes** [comment]
Route for 'digitalsignage_api' has been removed.
