### ISSUE TITLE
Linux Distribution is broken on Qmatic Portal

### ISSUE THREAD

**Issue by joche2** [qmatic/api-gateway#8]
Hello,

I am using Orchestra 6.2 Update 24 with Linux, i downloaded the latest version of the API Gateway 1.4.2.0 from the Qmatic Portal and this distribution never loads, this is because on the api-gateway file on line 67 are declared all the libraries that the API Gateway should use.

All of those libraries are wrong, like in the api-gateway file is looking for qp-api-gateway-1.4.1.0.jar and it has the qp-api-gateway-1.4.2.0.jar on the lib folder.

Here in github all source files are ok and that is how i managed to fix the problem, i would appretiate to update this package on the Qmatic Portal, to avoid any further issues with this.

Best Regards.

**Comment by grapatin** [comment]
Thanks, we will look into it and address that.
